remote: true

experienceLevel:
 internship: false
 entry: true
 associate: true
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: false
 part-time: false
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: true
 month: true
 week: true
 24 hours: true

positions:
  - Data Engineer
  - Data Scientist
  - Data Analyst
  - Snowflake
  - Python Developer
  - Data Architect
  - Solutions Engineer
  - Machine Learning Engineer

locations:
  - New York, United States
  - Boston, United States
  - Seattle, United States
  - San Francisco, United States

distance: 100

companyBlacklist:
  - Company1

titleBlacklist:
  - Java Developer
